---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msmega-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podlabel
  template:
    metadata:
      labels:
        app: podlabel
    spec:
      containers:
        - name: msmega
          image: localhost:5003/megaappimage
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: msmega-service1
spec:
  selector:
    app: podlabel
  ports:
    - port: 10000
      targetPort: 8000
  type: LoadBalancer
